services:
  database:
    container_name: work_at_olist_db
    image: postgres
    restart: no
    volumes:
      - ./.pgdata:/var/lib/postgresql/data
    env_file: .env
    ports:
      - 5438:5432
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -d $POSTGRES_DB -U $POSTGRES_USER"
        ]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    container_name: work_at_olist_app
    build:
      context: .
    volumes:
      - .:/code
    ports:
      - 8000:8000
    env_file: .env
    environment:
      DATABASE_URL: postgres://user01:pass01@database:5432/olistdb
    command: ./start.sh
    depends_on:
      database:
        condition: service_healthy