# Generated by Django 5.0.6 on 2024-06-11 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('edition', models.PositiveSmallIntegerField()),
                ('publication_year', models.PositiveSmallIntegerField()),
                ('authors', models.ManyToManyField(to='base.author')),
            ],
        ),
    ]
